### ISSUE TITLE
Execute build on Windows and macOS

### ISSUE THREAD

**Issue by ciscoo** [ciscoo/cxf-codegen-gradle#80]
Issues such as https://github.com/ciscoo/cxf-codegen-gradle/issues/74 may have been caught earlier. Prior to then, this plugin was primarily developed on KDE Neon and Linux Mint.

**Comment by ciscoo** [comment]
For Windows, seems to be mainly related to path which doesn't surprise me. After getting a minimal environment setup on my Windows machine, I see:

```logs
java.lang.AssertionError: 
Expecting actual:
  "
> Task :verify
C:\Users\fmate\AppData\Local\Temp\gradle-17919964218313887789\path\to\example.wsdl

BUILD SUCCESSFUL in 159ms
1 actionable task: 1 executed
"
to contain:
  "/path/to/example.wsdl" 
```

```logs
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/fmate/code/cxf-codegen-gradle/cxf-codegen-gradle/build/resources/functionalTest/io/mateo/cxf/codegen/configurationCacheCompatibility.gradle.kts
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
```
